export const factions = [
  'lightbearer', //0
  'mauler', //1
  'wilder', //2
  'graveborn', //3
  'celestial', //4
  'hypogean', //5
  'dimensional', //6
];

export const based = [
  'strength', //0
  'intelligence', //1
  'agility', //2
];

export const classes = [
  'warrior', //0
  'tank', //1
  'ranger', //2
  'mage', //3
  'support', //4
];

export const heroes = [
  {
    id: '001',
    name: 'athalia',
    faction: factions[4],
    base: based[2],
    class: classes[2],
  },
  {
    id: '002',
    name: 'elijah & Lailah',
    faction: factions[4],
    base: based[1],
    class: classes[4],
  },
  {
    id: '003',
    name: 'flora',
    faction: factions[4],
    base: based[1],
    class: classes[3],
  },
  {
    id: '004',
    name: 'orthos',
    faction: factions[4],
    base: based[0],
    class: classes[1],
  },
  {
    id: '005',
    name: 'talene',
    faction: factions[4],
    base: based[2],
    class: classes[4],
  },
  {
    id: '006',
    name: 'wu Kong',
    faction: factions[4],
    base: based[0],
    class: classes[0],
  },
  {
    id: '007',
    name: 'zaphreal',
    faction: factions[4],
    base: based[1],
    class: classes[3],
  },
  {
    id: '008',
    name: 'alna',
    faction: factions[4],
    base: based[2],
    class: classes[0],
  },
  {
    id: '101',
    name: 'ezizh',
    faction: factions[5],
    base: based[0],
    class: classes[4],
  },
  {
    id: '102',
    name: 'mehira',
    faction: factions[5],
    base: based[1],
    class: classes[3],
  },
  {
    id: '103',
    name: 'zolrath',
    faction: factions[5],
    base: based[2],
    class: classes[0],
  },
  {
    id: '104',
    name: 'khazard',
    faction: factions[5],
    base: based[1],
    class: classes[3],
  },
  {
    id: '105',
    name: 'mezoth',
    faction: factions[5],
    base: based[0],
    class: classes[1],
  },
  {
    id: '106',
    name: 'lucretia',
    faction: factions[5],
    base: based[2],
    class: classes[2],
  },
  {
    id: '107',
    name: 'mortas',
    faction: factions[5],
    base: based[2],
    class: classes[4],
  },
  {
    id: '201',
    name: 'estrilda',
    faction: factions[0],
    base: based[0],
    class: classes[0],
  },
  {
    id: '202',
    name: 'belinda',
    faction: factions[0],
    base: based[1],
    class: classes[3],
  },
  {
    id: '203',
    name: 'raine',
    faction: factions[0],
    base: based[2],
    class: classes[4],
  },
  {
    id: '204',
    name: 'rosaline',
    faction: factions[0],
    base: based[1],
    class: classes[4],
  },
  {
    id: '205',
    name: 'lucius',
    faction: factions[0],
    base: based[0],
    class: classes[1],
  },
  {
    id: '206',
    name: 'thane',
    faction: factions[0],
    base: based[2],
    class: classes[2],
  },
  {
    id: '207',
    name: 'fawkes',
    faction: factions[0],
    base: based[2],
    class: classes[2],
  },
  {
    id: '208',
    name: 'rowan',
    faction: factions[0],
    base: based[1],
    class: classes[4],
  },
  {
    id: '209',
    name: 'hendrik',
    faction: factions[0],
    base: based[0],
    class: classes[1],
  },
  {
    id: '210',
    name: 'gwyneth',
    faction: factions[0],
    base: based[0],
    class: classes[2],
  },
  {
    id: '211',
    name: 'rigby',
    faction: factions[0],
    base: based[0],
    class: classes[0],
  },
  {
    id: '212',
    name: 'cecilia',
    faction: factions[0],
    base: based[2],
    class: classes[2],
  },
  {
    id: '213',
    name: 'oscar',
    faction: factions[0],
    base: based[2],
    class: classes[2],
  },
  {
    id: '214',
    name: 'eluard',
    faction: factions[0],
    base: based[1],
    class: classes[3],
  },
  {
    id: '301',
    name: 'brutus',
    faction: factions[1],
    base: based[0],
    class: classes[1],
  },
  {
    id: '302',
    name: 'khaos',
    faction: factions[1],
    base: based[0],
    class: classes[0],
  },
  {
    id: '303',
    name: 'vurk',
    faction: factions[1],
    base: based[2],
    class: classes[2],
  },
  {
    id: '304',
    name: 'numisu',
    faction: factions[1],
    base: based[1],
    class: classes[4],
  },
  {
    id: '305',
    name: 'warek',
    faction: factions[1],
    base: based[0],
    class: classes[0],
  },
  {
    id: '306',
    name: 'skreg',
    faction: factions[1],
    base: based[0],
    class: classes[1],
  },
  {
    id: '307',
    name: 'safiya',
    faction: factions[1],
    base: based[1],
    class: classes[3],
  },
  {
    id: '308',
    name: 'satrana',
    faction: factions[1],
    base: based[1],
    class: classes[3],
  },
  {
    id: '309',
    name: 'antandra',
    faction: factions[1],
    base: based[2],
    class: classes[0],
  },
  {
    id: '310',
    name: 'tidus',
    faction: factions[1],
    base: based[2],
    class: classes[2],
  },
  {
    id: '311',
    name: 'skriath',
    faction: factions[1],
    base: based[1],
    class: classes[3],
  },
  {
    id: '312',
    name: 'anoki',
    faction: factions[1],
    base: based[0],
    class: classes[0],
  },
  {
    id: '313',
    name: 'drez',
    faction: factions[1],
    base: based[2],
    class: classes[2],
  },
  {
    id: '314',
    name: 'kren',
    faction: factions[1],
    base: based[2],
    class: classes[2],
  },
  {
    id: '401',
    name: 'nemora',
    faction: factions[2],
    base: based[1],
    class: classes[4],
  },
  {
    id: '402',
    name: 'kaz',
    faction: factions[2],
    base: based[2],
    class: classes[2],
  },
  {
    id: '403',
    name: 'lyca',
    faction: factions[2],
    base: based[2],
    class: classes[2],
  },
  {
    id: '404',
    name: 'ulmus',
    faction: factions[2],
    base: based[0],
    class: classes[1],
  },
  {
    id: '405',
    name: 'gorvo',
    faction: factions[2],
    base: based[0],
    class: classes[1],
  },
  {
    id: '406',
    name: 'eironn',
    faction: factions[2],
    base: based[2],
    class: classes[2],
  },
  {
    id: '407',
    name: 'tasi',
    faction: factions[2],
    base: based[1],
    class: classes[4],
  },
  {
    id: '408',
    name: 'seirus',
    faction: factions[2],
    base: based[0],
    class: classes[0],
  },
  {
    id: '409',
    name: 'lorsan',
    faction: factions[2],
    base: based[1],
    class: classes[3],
  },
  {
    id: '410',
    name: 'solise',
    faction: factions[2],
    base: based[1],
    class: classes[3],
  },
  {
    id: '411',
    name: 'saurus',
    faction: factions[2],
    base: based[0],
    class: classes[0],
  },
  {
    id: '412',
    name: 'pippa',
    faction: factions[2],
    base: based[1],
    class: classes[3],
  },
  {
    id: '413',
    name: 'respen',
    faction: factions[2],
    base: based[2],
    class: classes[2],
  },
  {
    id: '501',
    name: 'grezhul',
    faction: factions[3],
    base: based[0],
    class: classes[1],
  },
  {
    id: '502',
    name: 'shemira',
    faction: factions[3],
    base: based[1],
    class: classes[3],
  },
  {
    id: '503',
    name: 'oden',
    faction: factions[3],
    base: based[1],
    class: classes[3],
  },
  {
    id: '504',
    name: 'isabela',
    faction: factions[3],
    base: based[1],
    class: classes[3],
  },
  {
    id: '505',
    name: 'ferael',
    faction: factions[3],
    base: based[2],
    class: classes[2],
  },
  {
    id: '506',
    name: 'thoran',
    faction: factions[3],
    base: based[0],
    class: classes[1],
  },
  {
    id: '507',
    name: 'kelthur',
    faction: factions[3],
    base: based[2],
    class: classes[2],
  },
  {
    id: '508',
    name: 'nara',
    faction: factions[3],
    base: based[0],
    class: classes[0],
  },
  {
    id: '509',
    name: 'baden',
    faction: factions[3],
    base: based[2],
    class: classes[0],
  },
  {
    id: '510',
    name: 'izold',
    faction: factions[3],
    base: based[0],
    class: classes[0],
  },
  {
    id: '511',
    name: 'torne',
    faction: factions[3],
    base: based[0],
    class: classes[1],
  },
  {
    id: '512',
    name: 'daimon',
    faction: factions[3],
    base: based[0],
    class: classes[1],
  },
  {
    id: '513',
    name: 'theowyn',
    faction: factions[3],
    base: based[2],
    class: classes[2],
  },
  {
    id: '514',
    name: 'silas',
    faction: factions[3],
    base: based[1],
    class: classes[4],
  },
  {
    id: '601',
    name: 'arthur',
    faction: factions[6],
    base: based[0],
    class: classes[1],
  },
  {
    id: '602',
    name: 'nakoruru',
    faction: factions[6],
    base: based[2],
    class: classes[2],
  },
  {
    id: '603',
    name: 'ukyo',
    faction: factions[6],
    base: based[2],
    class: classes[0],
  },
  {
    id: '604',
    name: 'ezio',
    faction: factions[6],
    base: based[2],
    class: classes[2],
  },
  {
    id: '605',
    name: 'ainz Ooal Gown',
    faction: factions[6],
    base: based[1],
    class: classes[3],
  },
  {
    id: '606',
    name: 'albedo',
    faction: factions[6],
    base: based[0],
    class: classes[1],
  },
  {
    id: '607',
    name: 'joker',
    faction: factions[6],
    base: based[2],
    class: classes[2],
  },
  {
    id: '608',
    name: 'queen',
    faction: factions[6],
    base: based[0],
    class: classes[0],
  },
];
