import { ascentions } from '../app.js';

export const heroesUser = [
  {
    id: '001',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '002',
    ascention: ascentions[3],
    si: 20,
    furniture: 3,
  },
  {
    id: '003',
    ascention: ascentions[1],
    si: null,
    furniture: 0,
  },
  {
    id: '004',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '005',
    ascention: ascentions[3],
    si: 30,
    furniture: 5,
  },
  {
    id: '006',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '007',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '008',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '101',
    ascention: ascentions[2],
    si: 20,
    furniture: 0,
  },
  {
    id: '102',
    ascention: ascentions[1],
    si: null,
    furniture: 0,
  },
  {
    id: '103',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '104',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '105',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '106',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '107',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '201',
    ascention: ascentions[3],
    si: 10,
    furniture: 4,
  },
  {
    id: '202',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '203',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '204',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '205',
    ascention: ascentions[3],
    si: 20,
    furniture: 4,
  },
  {
    id: '206',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '207',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '208',
    ascention: ascentions[3],
    si: 30,
    furniture: 9,
  },
  {
    id: '209',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '210',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '211',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '212',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '213',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '214',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '301',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '302',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '303',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '304',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '305',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '306',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '307',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '308',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '309',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '310',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '311',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '312',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '313',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '314',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '401',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '402',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '403',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '404',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '405',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '406',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '407',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '408',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '409',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '410',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '411',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '412',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '413',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '501',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '502',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '503',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '504',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '505',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '506',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '507',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '508',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '509',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '510',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '511',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '512',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '513',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '514',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '601',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '602',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '603',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '604',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '605',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '606',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '607',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
  {
    id: '608',
    ascention: ascentions[0],
    si: null,
    furniture: 0,
  },
];
