export const userHeroes = [
  {
    id: '001',
    ascention: 'ascended',
    si: 20,
    furniture: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '002',
    ascention: 'ascended',
    si: 20,
    furniture: 3,
    gear: [2, 2, 2, 2],
  },
  {
    id: '003',
    ascention: 'ascended',
    si: 20,
    furniture: 3,
    gear: [2, 2, 2, 2],
  },
  {
    id: '004',
    ascention: 'eliteP',
  },
  {
    id: '005',
    ascention: 'ascended',
    si: 30,
    furniture: 9,
    gear: [2, 2, 2, 2],
  },
  {
    id: '006',
    ascention: 'mythicP',
    si: 20,
    gear: [2, 2, 2, 2],
  },
  {
    id: '007',
    ascention: 'legendary',
  },
  {
    id: '008',
    ascention: 'ascended',
    si: 30,
    furniture: 9,
    gear: [3, 3, 3, 3],
  },
  {
    id: '009',
    ascention: 'eliteP',
  },
  {
    id: '010',
    ascention: 'none',
  },
  {
    id: '011',
    ascention: 'none',
  },
  {
    id: '012',
    ascention: 'mythic',
    si: '10',
    gear: [2, 2, 2, 2],
  },
  {
    id: '013',
    ascention: 'none',
  },
  {
    id: '101',
    ascention: 'ascended',
    si: 30,
    furniture: 9,
    gear: [2, 2, 2, 2],
  },
  {
    id: '102',
    ascention: 'mythicP',
    si: 20,
    gear: [2, 2, 2, 2],
  },
  {
    id: '103',
    ascention: 'mythicP',
    si: 10,
    gear: [2, 2, 2, 2],
  },
  {
    id: '104',
    ascention: 'ascended',
    si: 30,
    furniture: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '105',
    ascention: 'legendary',
  },
  {
    id: '106',
    ascention: 'ascended',
    stars: 1,
    si: 30,
    furniture: 9,
    engraving: 60,
    gear: [3, 3, 3, 3],
  },
  {
    id: '107',
    ascention: 'eliteP',
    gear: [2, 2, 2, 2],
  },
  {
    id: '108',
    ascention: 'none',
  },
  {
    id: '109',
    ascention: 'none',
  },
  {
    id: '110',
    ascention: 'elite',
  },
  {
    id: '111',
    ascention: 'legendaryP',
  },
  {
    id: '201',
    ascention: 'ascended',
    stars: 5,
    si: 20,
    furniture: 5,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '202',
    ascention: 'ascended',
    stars: 5,
    si: 20,
    furniture: 3,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '203',
    ascention: 'ascended',
    stars: 2,
    si: 30,
    furniture: 3,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '204',
    ascention: 'ascended',
    stars: 5,
    si: 20,
    furniture: 8,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '205',
    ascention: 'ascended',
    stars: 5,
    si: 20,
    furniture: 4,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '206',
    ascention: 'ascended',
    stars: 1,
    si: 10,
    engraving: 0,
  },
  {
    id: '207',
    ascention: 'ascended',
    stars: 5,
    si: 20,
    furniture: 5,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '208',
    ascention: 'ascended',
    stars: 5,
    si: 30,
    furniture: 9,
    engraving: 0,
    gear: [3, 3, 3, 3],
  },
  {
    id: '209',
    ascention: 'ascended',
    stars: 1,
    si: 10,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '210',
    ascention: 'ascended',
    stars: 5,
    si: 20,
    furniture: 9,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '211',
    ascention: 'ascended',
    si: 10,
  },
  {
    id: '212',
    ascention: 'ascended',
    stars: 1,
    si: 10,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '213',
    ascention: 'ascended',
    stars: 2,
    si: 10,
    engraving: 0,
  },
  {
    id: '214',
    ascention: 'ascended',
    si: 10,
  },
  {
    id: '215',
    ascention: 'mythicP',
    si: 0,
  },
  {
    id: '216',
    ascention: 'legendary',
  },
  {
    id: '217',
    ascention: 'mythicP',
    si: 10,
  },
  {
    id: '218',
    ascention: 'ascended',
    stars: 1,
    si: 30,
    furniture: 4,
    engraving: 30,
    gear: [4, 4, 4, 4],
  },
  {
    id: '301',
    ascention: 'ascended',
    stars: 5,
    si: 20,
    furniture: 3,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '302',
    ascention: 'ascended',
    stars: 4,
    si: 10,
  },
  {
    id: '303',
    ascention: 'mythicP',
    si: 10,
  },
  {
    id: '304',
    ascention: 'ascended',
    stars: 1,
    si: 10,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '305',
    ascention: 'ascended',
    stars: 3,
    si: 20,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '306',
    ascention: 'ascended',
    stars: 5,
    si: 30,
    furniture: 9,
    engraving: 0,
    gear: [3, 3, 3, 3],
  },
  {
    id: '307',
    ascention: 'ascended',
    stars: 3,
    si: 20,
    furniture: 3,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '308',
    ascention: 'ascended',
    si: 10,
  },
  {
    id: '309',
    ascention: 'ascended',
    stars: 2,
    si: 10,
    furniture: 2,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '310',
    ascention: 'ascended',
    stars: 5,
    si: 30,
    furniture: 9,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '311',
    ascention: 'ascended',
    stars: 5,
    si: 30,
    furniture: 6,
    engraving: 0,
    gear: [3, 3, 3, 3],
  },
  {
    id: '312',
    ascention: 'legendaryP',
  },
  {
    id: '313',
    ascention: 'mythicP',
    si: 20,
    gear: [2, 2, 2, 2],
  },
  {
    id: '314',
    ascention: 'ascended',
    stars: 3,
    si: 20,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '315',
    ascention: 'mithicP',
    si: 10,
    gear: [2, 2, 2, 2],
  },
  {
    id: '316',
    ascention: 'legendaryP',
  },
  {
    id: '317',
    ascention: 'elite',
  },
  {
    id: '318',
    ascention: 'elite',
  },
  {
    id: '401',
    ascention: 'mythic',
    si: 10,
  },
  {
    id: '402',
    ascention: 'ascended',
    stars: 1,
    si: 10,
    engraving: 0,
  },
  {
    id: '403',
    ascention: 'ascended',
    stars: 5,
    si: 30,
    furniture: 9,
    engraving: 0,
    gear: [3, 3, 3, 3],
  },
  {
    id: '404',
    ascention: 'eliteP',
  },
  {
    id: '405',
    ascention: 'ascended',
    si: 10,
    gear: [2, 2, 2, 2],
  },
  {
    id: '406',
    ascention: 'ascended',
    stars: 5,
    si: 30,
    furniture: 9,
    engraving: 0,
    gear: [3, 3, 3, 3],
  },
  {
    id: '407',
    ascention: 'ascended',
    stars: 5,
    si: 20,
    furniture: 9,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '408',
    ascention: 'ascended',
    si: 10,
  },
  {
    id: '409',
    ascention: 'ascended',
    stars: 3,
    si: 20,
    furniture: 9,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '410',
    ascention: 'ascended',
    stars: 5,
    si: 10,
    furniture: 2,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '411',
    ascention: 'ascended',
    stars: 5,
    si: 30,
    furniture: 9,
    engraving: 0,
    gear: [3, 3, 3, 3],
  },
  {
    id: '412',
    ascention: 'ascended',
    stars: 1,
    si: 30,
    furniture: 9,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '413',
    ascention: 'mythicP',
    si: 10,
    gear: [2, 2, 2, 2],
  },
  {
    id: '414',
    ascention: 'ascended',
    stars: 1,
    si: 30,
    furniture: 9,
    engraving: 30,
    gear: [3, 3, 3, 3],
  },
  {
    id: '415',
    ascention: 'mythic',
    si: 10,
    gear: [2, 2, 2, 2],
  },
  {
    id: '416',
    ascention: 'legendaryP',
  },
  {
    id: '417',
    ascention: 'none',
  },
  {
    id: '501',
    ascention: 'ascended',
    stars: 5,
    si: 30,
    furniture: 9,
    engraving: 80,
    gear: [4, 4, 4, 4],
  },
  {
    id: '502',
    ascention: 'ascended',
    stars: 5,
    si: 20,
    furniture: 9,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '503',
    ascention: 'ascended',
    stars: 2,
    si: 30,
    furniture: 9,
    engraving: 30,
    gear: [3, 3, 3, 3],
  },
  {
    id: '504',
    ascention: 'mythicP',
    si: 10,
  },
  {
    id: '505',
    ascention: 'ascended',
    stars: 5,
    si: 30,
    furniture: 9,
    engraving: 30,
    gear: [4, 4, 4, 3],
  },
  {
    id: '506',
    ascention: 'ascended',
    stars: 5,
    si: 30,
    furniture: 9,
    engraving: 0,
    gear: [3, 3, 3, 3],
  },
  {
    id: '507',
    ascention: 'ascended',
    stars: 5,
    si: 20,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '508',
    ascention: 'ascended',
    si: 10,
    gear: [2, 2, 2, 2],
  },
  {
    id: '509',
    ascention: 'ascended',
    si: 10,
    gear: [2, 2, 2, 2],
  },
  {
    id: '510',
    ascention: 'ascended',
    stars: 5,
    si: 30,
    furniture: 9,
    engraving: 0,
    gear: [3, 3, 3, 3],
  },
  {
    id: '511',
    ascention: 'eliteP',
  },
  {
    id: '512',
    ascention: 'ascended',
    stars: 4,
    si: 30,
    furniture: 9,
    engraving: 0,
    gear: [3, 3, 3, 3],
  },
  {
    id: '513',
    ascention: 'mythicP',
    si: 10,
  },
  {
    id: '514',
    ascention: 'ascended',
    stars: 4,
    si: 30,
    furniture: 9,
    engraving: 30,
    gear: [3, 3, 3, 3],
  },
  {
    id: '515',
    ascention: 'ascended',
    stars: 3,
    si: 20,
    furniture: 0,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '516',
    ascention: 'ascended',
    si: 10,
    gear: [2, 2, 2, 2],
  },
  {
    id: '517',
    ascention: 'legendaryP',
  },
  {
    id: '518',
    ascention: 'legendary',
  },
  {
    id: '601',
    ascention: 'ascended',
    stars: 5,
    si: 30,
    furniture: 7,
    engraving: 0,
    gear: [3, 3, 3, 3],
  },
  {
    id: '602',
    ascention: 'none',
  },
  {
    id: '603',
    ascention: 'none',
  },
  {
    id: '604',
    ascention: 'ascended',
    stars: 5,
    si: 30,
    furniture: 9,
    engraving: 0,
    gear: [3, 3, 3, 3],
  },
  {
    id: '605',
    ascention: 'ascended',
    stars: 5,
    si: 30,
    furniture: 9,
    engraving: 60,
    gear: [3, 3, 3, 3],
  },
  {
    id: '606',
    ascention: 'ascended',
    stars: 5,
    si: 30,
    furniture: 9,
    engraving: 30,
    gear: [3, 3, 3, 3],
  },
  {
    id: '607',
    ascention: 'ascended',
    stars: 5,
    si: 20,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '608',
    ascention: 'ascended',
    stars: 5,
    si: 20,
    furniture: 6,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '609',
    ascention: 'ascended',
    stars: 5,
    si: 20,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '610',
    ascention: 'ascended',
    stars: 5,
    si: 30,
    furniture: 9,
    engraving: 0,
    gear: [3, 3, 3, 3],
  },
  {
    id: '611',
    ascention: 'ascended',
    stars: 5,
    si: 20,
    furniture: 9,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
  {
    id: '612',
    ascention: 'ascended',
    stars: 5,
    si: 20,
    furniture: 0,
    engraving: 0,
    gear: [2, 2, 2, 2],
  },
];
